name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: |
        go get -v -t -d ./...
        make deps
      env:
        GO111MODULE: 'on'
    - name: Lint
      run: make lint
      env:
        PATH: '$PATH:$GOPATH/bin'
    - name: Test
      run: make cover
      env:
        PATH: '$PATH:$GOPATH/bin'
    - name: Build
      run: make build
      env:
        PATH: '$PATH:$GOPATH/bin'
