name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        go get -v -t -d ./...
        make deps
      env:
        GO111MODULE: 'on'
    - name: Lint
      run: PATH="$(go env GOPATH)/bin:$PATH" make lint
    - name: Test
      run: make cover
    - name: Code Climate
      run: |
        ./cc-test-reporter format-coverage -t gocov c.out
        ./cc-test-reporter upload-coverage
      env:
        GIT_BRANCH: ${{ github.ref }}
        GIT_COMMIT_SHA: ${{ github.sha }}
    - name: Build
      run: PATH="$(go env GOPATH)/bin:$PATH" VERSION=${GITHUB_REF} make build
      env:
        CI: true
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/chrome-bookmarks.alfredworkflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
